language: cpp

compiler: gcc

solution: Trace.sln

branches:
  only:
    - build

addons:
  apt:
    packages:
    - cmake
    - libpcap-dev

before_script: cd build

script: cmake ../cmake/

notifications:
  email: false
