language: cpp

compiler: gcc

sudo: require

solution: Trace.sln

branches:
  only:
    - build

install: sudo apt-get install libpcap-dev

before_script:
  - cd build
  - find -iname "pcap.h"

script: cmake ../cmake/

notifications:
  email: false
